### ISSUE TITLE
 小小的功能建議 #20 (enhancement)

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#10]
[monkey03297](https://github.com/monkey03297) commented [on 1 May 2021](https://github.com/ack7139/thprac/issues/20#issue-873597906)
風神錄六面Boss的終符，有隨著血條越少，彈速越快的現象。
希望可以做為選項，以利練習。

[Kerbinator-CN](https://github.com/Kerbinator-CN) commented [on 1 Sep 2021](https://github.com/ack7139/thprac/issues/20#issuecomment-909890095)
呃，這個我覺得沒有問題，神德其實不是說隨著血量改變彈速
只有開卡後三十秒彈速以及發彈頻率增加一次，之後就不再變化，與血量無關。
用練習器開和實戰是完全一致的，因此沒有什麼問題。
見 [https://thwiki.cc/游戏攻略/STG血量数据](https://thwiki.cc/%E6%B8%B8%E6%88%8F%E6%94%BB%E7%95%A5/STG%E8%A1%80%E9%87%8F%E6%95%B0%E6%8D%AE)
(應該可以close)

**Comment by 32th-System** [comment]
Same issue as https://github.com/touhouworldcup/thprac/issues/42, fixed in https://github.com/touhouworldcup/thprac/commit/a12c09cb1622fadf30b1b92a6b7f4c8f10368958
