### ISSUE TITLE
18.5: "Force Wave" doesn't work correctly after the first wave

### ISSUE THREAD

**Issue by webbedspace** [touhouworldcup/thprac#114]
For example, try these options:
![image](https://user-images.githubusercontent.com/83939/195253173-fba50b83-54a5-43cb-b335-83b2cb9a8d83.png)
Wave01 of End Of Market is "FairyWave Type Aim 1". Wave02 is "Big Fairy Splash".
However, with these settings, BOTH waves become "FairyWave Type Aim 1". Only when reaching the "None" wave does the wave change.

You can change Wave01 to Wave02 and vice-versa to make both waves "Big Fairy Splash".

**Comment by 32th-System** [comment]
I'll probably just get rid of that feature and replace it with a menu where you select a wave when the game actually tries to randomly select then shoot the wave. It's the only thing that wouldn't be a hacky hardcoded mess anyways
