### ISSUE TITLE
18.5: Consider changing terminology of "Wave" (chapter of a stage) vs "Wave" (randomly selected attack pattern)

### ISSUE THREAD

**Issue by webbedspace** [touhouworldcup/thprac#115]
This gets confusing because of how the "Force Wave" UI is set up: You can have "Wave01" in the slot "Wave 1", and both uses of the word "Wave" mean completely different things.

I think the UI should use "Attack" to refer to attack patterns, and use "Wave" to refer to chapters in a stage. So, for instance, "Great Fairy Flower Cyclone" is an "Attack" rather than a "Wave".

**Comment by 32th-System** [comment]
The entire "Force Wave" system is something I tacked on because I wanted a way practice specific enemy wave patterns. I'll come up with a better system where whenever a wave is fired you get a menu to choose which wave is fired

**Comment by 32th-System** [comment]
wait I already commented something similair

**Comment by webbedspace** [comment]
Déjà vu?

**Comment by 32th-System** [comment]
No I just forgor 💀
