### ISSUE TITLE
TH11: trying to practice warp on stage 4 crashes on loading

### ISSUE THREAD

**Issue by c1ayman2** [touhouworldcup/thprac#119]
additionally trying to skip to boss on stage 4 without dialogue ends up with player character/no enemies/unable to shoot.

trying to warp past the initial map section results on a crash/hang during loading.

**Comment by 32th-System** [comment]
Is your stage04.ecl modified?

**Comment by c1ayman2** [comment]
i don't see such a file. i imagine such a change would need to be intentional?.
i am using the english patched version. (th11e.exe)
speaking of which, i just tried the JP version, and the problem does not occur on it. to be honest, i don't think english matters much for thprac.

**Comment by 32th-System** [comment]
stage04.ecl is in th11.dat. The English patch modifies it in a way that breaks thprac. Static English patches in general aren't supported by thprac. If you want to use thprac and an English patch, you should use thcrap
