### ISSUE TITLE
th08: "Ephemerality 137" option is not available on easy difficulty in practice mode.

### ISSUE THREAD

**Issue by pingval** [touhouworldcup/thprac#126]
as the title says. I found it by accident.
Screenshot: 
![Ephemerality 137 easy](https://user-images.githubusercontent.com/40169989/219953155-c0fa945b-28f8-479c-aa12-6921b361c826.png)

**Comment by hoangcaominh** [comment]
Ephemerality 137 does not have an easy difficulty variation, as shown in the spell practice menu
![th081](https://user-images.githubusercontent.com/35196884/219962638-6661dcf8-3501-48ca-8f57-36d92e522dde.png)
