### ISSUE TITLE
[Linux & Steam] Can't apply patch on Steam version of th16

### ISSUE THREAD

**Issue by LeSaRo** [touhouworldcup/thprac#129]
I tried to run thprac from Steam & Lutris but I can't apply the patch. It recognizes the game, but I can't launch it from the GUI and launching the game then clicking on "Apply thprac to ongoing game" says no games were found. On non-steam games it works.

**Comment by 32th-System** [comment]
That is because the Steam versions have SteamDRM. Launching the game with thcrap should work

**Comment by LeSaRo** [comment]
I should mention that I run the game through thcrap (albeit with a wrapper script because running thcrap through the shortcut launches without the Steam save file)

**Comment by 32th-System** [comment]
assuming that the game and thprac run in the same wineprefix, it should work

**Comment by LeSaRo** [comment]
I tried to run thprac using the same launch option with the same Proton version and it still doesn't see the game.

**Comment by 32th-System** [comment]
The same launch option and same Proton version could still be launching in a different wineprefix (probably is). Run `export WINEPREFIX=/home/<username>/.steam/steam/steamapps/compatdata/<app id>/pfx`

**Comment by LeSaRo** [comment]
I tried both running it as a command (modifying the path) and as a launch option (removing the export) and both times it doesn't work.

**Comment by 32th-System** [comment]
hold on, what are you using to launch the Steam version of your game with thcrap?

**Comment by LeSaRo** [comment]
Steam itself with [thcrap-proton](https://github.com/tactikauan/thcrap-steam-proton-wrapper). Running the game standalone doesn't use the Steam save.

**Comment by 32th-System** [comment]
looks like it generates some command line output. Could I see that?

**Comment by LeSaRo** [comment]
Using the instructions returns `Proton: No compat data path?`.

**Comment by 32th-System** [comment]
Regarding those other instructions I gave you: use the wine binary from the Proton versioin

**Comment by LeSaRo** [comment]
Actualy I managed to get the generated command.
```
 /home/<username>/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=745880 -- /home/v/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /media/data/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --verb=waitforexitandrun -- /home/<username>/.local/share/Steam/compatibilitytools.d/GE-Proton7-49/proton waitforexitandrun '/media/data/Jeux/Touhou/thcrap/thcrap_loader.exe' lang_en.js /media/data/SteamLibrary/steamapps/common/th16/th16.exe
```

**Comment by 32th-System** [comment]
`WINEPREFIX=/home/<username>/.local/share/Steam/steamapps/compatdata/745880/pfx/ /home/<username>/.local/share/Steam/compatibilitytools.d/GE-Proton7-49/files/bin/wine /path/to/thprac.exe`

**Comment by LeSaRo** [comment]
Now it works! Thanks!

**Comment by 32th-System** [comment]
on a semi related note, I would also recommend you check out https://github.com/major-gnuisance/thcrap-linux-ez/blob/main/thcrap_auto_gui.py

**Comment by LeSaRo** [comment]
Ok, I'll take a look at it later.
