### ISSUE TITLE
[UM] Visual discrepancy when buying actives mid-stage

### ISSUE THREAD

**Issue by Guy-L** [touhouworldcup/thprac#146]
This isn't really an issue that needs fixing, but more of a technical quirk of UM that I think I should bring to your attention.<br>It's perfectly fine if you decide not to fix this and you can close the issue.

In the vanilla game, when you buy an active in the shop, the game automatically makes this your currently selected active. This also happens when you use the Market Manip option to buy an active. However, for some reason, the ANM of your currently selected active card in the bottom-left corner does not get updated when this swap happens. Instead, the stage transition has a routine which checks for and corrects the visual discrepancy. Very ZUN move to add a safeguard to recover from an easy-to-fix bug while leaving a replay breaking glitch in the same part of the code.

![image](https://github.com/touhouworldcup/thprac/assets/55163797/f8679aef-aca1-49bc-a42a-1d958a746cb9)

![image](https://github.com/touhouworldcup/thprac/assets/55163797/c4c6f69a-07b6-492b-b5b5-f80faec336c8)

When you use the F11 option to open a shop mid-run and buy an active, the stage transition routine isn't there to fix the visual discrepancy. So once you exit the shop, the selected active card UI will still show your previously selected card, but when you press C, the effects of the new card will take place. The issue fixes itself when you press D (in some situations this makes you swap into the card that's already on the UI, which is pretty confusing).

![image](https://github.com/touhouworldcup/thprac/assets/55163797/b11f6a00-4a1d-4437-a5da-863fac37f70f)

This issue doesn't matter since you're not meant to continue runs after using the F11 option anyway. I just think it's a neat quirk worth sharing.

**Comment by 32th-System** [comment]
> Instead, the stage transition has a routine which checks for and corrects the visual discrepancy

You seem to have figured this out already, could you tell be where to look for this code?

**Comment by Guy-L** [comment]
I resolved the issue in my fork, I'll make a new pull request once I'm done with my last planned change.
