### ISSUE TITLE
[UFO] thprac not recognising touhou 12

### ISSUE THREAD

**Issue by caliope17** [touhouworldcup/thprac#150]
Firstly, thprac recognise UFO and fail to patch it. Then, it do not recognise a game is launched for every try onward.

The issue is with 2.2.1.4 and it seems to work fine with 2.2.1.3, I'm on windows 10.

**Comment by 32th-System** [comment]
could you share some more details about the specific version of TH12 you use?

**Comment by caliope17** [comment]
Where can I find this information ? If I launch the game, under the boat of Reimu there is 1.00b but I don't think it what you want.

**Comment by 32th-System** [comment]
Well, if you are using an English patch that modifies th12.dat and th12.exe directly, you shouldn't because that does break thprac

**Comment by caliope17** [comment]
I believe it does not modify the .dat and .exe directly because the last modification is from 2009. Plus, all of the data for thcrap is in an other folder (and finally, if I remember correctly, thcrap or at least the patch I downloaded said it does not modify the game data directly). Also, why would 2.2.1.3 work if the patch modifies directly the data ?

**Comment by caliope17** [comment]
Would you want a video of what happens ? I could maybe try ...
