### ISSUE TITLE
TH19 is not in the "Add thcrap configs..." option

### ISSUE THREAD

**Issue by SilverSlinky606** [touhouworldcup/thprac#161]

**Comment by 32th-System** [comment]
I want to do a lot more for the next thprac release, but I did implement a fix for this. In the meantime, you could download a beta version from [https://nightly.link/touhouworldcup/thprac/workflows/main/master/thprac.zip](https://nightly.link/touhouworldcup/thprac/workflows/main/master/thprac.zip) (it will automatically update to the next version once it comes out)

**Comment by acm233** [comment]
> I want to do a lot more for the next thprac release, but I did implement a fix for this. In the meantime, you could download a beta version from [https://nightly.link/touhouworldcup/thprac/workflows/main/master/thprac.zip](https://nightly.link/touhouworldcup/thprac/workflows/main/master/thprac.zip) (it will automatically update to the next version once it comes out)

OK, thank you

**Comment by FortuneTTS** [comment]
> I want to do a lot more for the next thprac release, but I did implement a fix for this. In the meantime, you could download a beta version from https://nightly.link/touhouworldcup/thprac/workflows/main/master/thprac.zip (it will automatically update to the next version once it comes out)

the link is dead

**Comment by 32th-System** [comment]
I made a new release, so you won't need to use the dev build anymore
