### ISSUE TITLE
Windows XP isn't supported by thprac v2.2.1.3 and later.

### ISSUE THREAD

**Issue by VincentDirac** [touhouworldcup/thprac#186]
Someone tell me that they can't use thprac's latest version in Windows XP. Then I check it out and find it's sure. I test sevaral versions of thprac, and then find when using thprac v2.2.1.3 and later, the program will report that <b>“Unable to locate program input point InitializeCriticalSectionEx on Dynamic Link Library Kernel32.dll”</b>. I notice that thprac support C++ 20 after version 2.2.0.0. Maybe this bug is associated with it. I know Windows XP is too old and can't even support some newest touhou game. I don't know if the developers would like to fix the bug, but I think we can note that “thprac would not support Windows XP" in README.md. Thanks!

**Comment by 32th-System** [comment]
welp, looks like Windows XP support is no more. I tried to set up the build system in system in such a way that I could use the latest compiler, and would have access to C++20 while still being able to support Windows XP. The only problem with this approach is that supporting XP in such a way is highly volatile. Depending on when I compile thprac, the compiler could randomly put something in that breaks Windows XP support. I decided that the moment that happens, Windows XP support just gets dropped, and XP users would need to use [One-Core-AP)](https://github.com/Skulltrail192/One-Core-API-Binaries). So consider Windows XP support officially dropped
