### ISSUE TITLE
 TH12: Grudge Bow "The Bow of Genzanmi Yorimasa" only has 2 phases selectable, not all 4

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#26]
@[webbedspace](https://github.com/webbedspace)
webbedspace commented [on 12 Nov 2021](https://github.com/ack7139/thprac/issues/48#issue-1051580040)
This spell has 4 phases, each separated by a cancel:
- Sparse fast bullets from alternating sides
- Dense slow bullets from both sides
- Sparse fast bullets from both sides
- Dense medium-speed bullets from both sides

Currently you can only select phases 1 and 4 (I think).

**Comment by hoangcaominh** [comment]
Grudge bow now has 4 phases and the timeout phase as https://github.com/touhouworldcup/thprac/pull/111#issue-1384134082
