### ISSUE TITLE
thcrap support expects the old thcrap_configure to be present

### ISSUE THREAD

**Issue by inakilbss** [touhouworldcup/thprac#45]
The check for thcrap folder validity includes checking that thcrap_configure.exe exists, which makes using thcrap through the launcher inconvenient, as thcrap_configure.exe is deleted every time a game is opened with thcrap and the folder is validated every time the launcher opens

**Comment by 32th-System** [comment]
![grafik](https://user-images.githubusercontent.com/23106652/174077445-006ba783-1716-400f-bcad-a623d18f0130.png)
No

**Comment by inakilbss** [comment]
wait when was this fixed

**Comment by hoangcaominh** [comment]
> wait when was this fixed

21 days ago I think.
I think we can close this issue now.

**Comment by 32th-System** [comment]
https://github.com/touhouworldcup/thprac/commit/e4261f59ca4eb61c3a9efcbd2aae1ead8b1b8b51
