### ISSUE TITLE
thprac says "network error" when i press "check for updates"

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#48]
![изображение](https://user-images.githubusercontent.com/62563494/173322816-8a444d46-a396-4cd2-8f3f-b6e974c877ef.png)
though it could be roskomnadzor blocking random stuff as usual

**Comment by 32th-System** [comment]
This is a problem even with old thprac on any Windows version older than 10

**Comment by toimine** [comment]
bruh
