### ISSUE TITLE
the settings tab still refers to ack's stuff

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#5]
![изображение](https://user-images.githubusercontent.com/62563494/170879118-54301fa3-357e-4409-9b0c-3c79f7f3431e.png)

**Comment by 32th-System** [comment]
Since you're here having opened the first issue in this repo, would you close the issues I've resolved in the original thprac repo and transfer the ones I haven't resolved to this one?

**Comment by toimine** [comment]
> Since you're here having opened the first issue in this repo, would you close the issues I've resolved in the original thprac repo and transfer the ones I haven't resolved to this one?

alright hold on
