### ISSUE TITLE
the manual doesn't explain hotkeys

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#50]
for example, i've only now discovered that there's an extra menu that appears when you press L, and it's not mentioned anywhere
ideally hotkey explanation would be great as a separate .txt file, or i'd lose myself in manual.txt

**Comment by hoangcaominh** [comment]
The extra menu was still under development and we kinda overlooked it when version 2.1.0.0 was released. But yeah I agree there should be a detailed manual for most of thprac features.

**Comment by 32th-System** [comment]
Fixed in https://github.com/touhouworldcup/thprac/commit/1d7df75dcc3bd83243309b9cb639e6fb5fe9e852
