### ISSUE TITLE
vpatch stops working if you press F10 to go out of fullscreen, then go back into fullscreen

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#52]
i'm not sure if F10 is a normal in-game hotkey or a thprac one, but that happens

**Comment by 32th-System** [comment]
F10 doesn't do anything for me with or without thprac

**Comment by 32th-System** [comment]
Just realized I was testing with th07 because I somehow thought you were referring to TH07 in particular? I must've conflated some issues

**Comment by toimine** [comment]
yeah that's a different issue

**Comment by 32th-System** [comment]
UPDATE: th11, th12, th125, th128 and th13 all have a feature to cycle between the 3 window resolutions and fullscreen mode with F10. In all of those games except for th128, doing that with vpatch attached with break all vpatch features. This is a bug with vpatch itself
