### ISSUE TITLE
enable L for all games

### ISSUE THREAD

**Issue by toimine** [touhouworldcup/thprac#54]
- [ ] alcostg
- [ ] th06
- [ ] th07
- [ ] th08
- [ ] th09
- [ ] th10
- [ ] th11
- [ ] th12
- [ ] th12.8
- [X] th13
- [ ] th14
- [ ] th15
- [ ] th16
- [ ] th17
- [ ] th18

**Comment by 32th-System** [comment]
Bonus feature: making those numbers editable to implement #33
