### ISSUE TITLE
Game Speed > Debug acc. has confusing tooltip label

### ISSUE THREAD

**Issue by webbedspace** [touhouworldcup/thprac#62]
![image](https://user-images.githubusercontent.com/83939/174808440-e7b782ae-c379-44c0-99c8-32f31e66dcfd.png)
See above image

**Comment by 32th-System** [comment]
"Debug acc." stands for "Debug acceleration" and will make it so that holding down the space bar makes the game run at the maximum speed your PC can handle. It is only properly implemented in th13

**Comment by 32th-System** [comment]
This issue is now superceded by https://github.com/touhouworldcup/thprac/issues/66
