### ISSUE TITLE
Idea: visual option for "Danmaku Paranoia" that forces sprites that match the hitboxes (inverse of #63)

### ISSUE THREAD

**Issue by webbedspace** [touhouworldcup/thprac#64]
![image](https://user-images.githubusercontent.com/83939/174992533-acc70d16-8bc2-4b26-ae51-58a249072a5f.png)
Danmaku Paranoia might be the strangest and boldest spell design in SA – unlike those two Kanako spells, it uses incorrect bullet hitboxes *on purpose* to explicitly trick the player and communicate the spell's thematic identity of "paranoid delusion". That being said, having already proposed #63, I also want to propose an option that "pulls back the curtain" and replaces the mint bullets' sprites with different sprites that match the actual hitbox.

I know this spell is not relevant for most SA categories nor even particularly difficult in and of itself, so I understand you may not really want to dedicate resources to this when there's hotter stuff on the table. I also don't really understand how this spell works under the bonnet, and whether the bullets' actual hitboxes map cleanly to an existing bullet sprite (for all I know, those are completely unique bullets that reuse the mint sprite, similar to the buggy yellow bullets in "Modern Divine Spirit World") so this may not make sense at all.

**Comment by inakilbss** [comment]
first time i hear of it having incorrect hitboxes

**Comment by webbedspace** [comment]
Actually, tell me… do the mint bullets in other SA sections have hitboxes as generous as those in the screenshot above?

**Comment by Altair357** [comment]
![image](https://user-images.githubusercontent.com/3735962/185355887-fa6704d7-f6b8-4cb3-9dc8-8e074f73e95a.png)
They're all the same. I don't think it's an SA thing either. Touhou bullets are just........................... like that.
