### ISSUE TITLE
A bug report and A suggestion for future features of “L” key HUD

### ISSUE THREAD

**Issue by AkitsukiM** [touhouworldcup/thprac#68]
A bug report: Some data wouldn’t be reset after “give up and retry” in th13 (Items, Cancel; Blue, Grey, Purple, Green, Active trance, Passive trance; Miss, Bomb, SC Enter, SC Get, etc.)
A suggestion: Add miss count, bomb count, use-C-key count, key mapping and system time display for all Touhou official games (system time display would be useful in TWC and other competitive STG matches)

**Comment by 32th-System** [comment]
When it comes to showing system time for TWC matches it depends if having this HUD open would even be allowed on TWC
