### ISSUE TITLE
When thprac is started, the Window Style of the game window changes and the screen size also changes.

### ISSUE THREAD

**Issue by es2z** [touhouworldcup/thprac#71]
It seems that the WS_THICKFRAME window style flag is turned on at run time.
This phenomenon has been present since v2.1.0.0.

I have confirmed the reproduction of this phenomenon by both of the following two methods.
Launched the game by thprac.exe
Running thprac.exe while the game is running

**Comment by 32th-System** [comment]
This is intentional. It also shows resizing the window as you want

**Comment by es2z** [comment]
Thank you very much.
