### ISSUE TITLE
"Unlock monitor refresh rate" disappeared in v2.1.3.0

### ISSUE THREAD

**Issue by STARBOWBREAK6** [touhouworldcup/thprac#77]
解锁屏幕刷新率 在最新的2.1.3.0版本中消失了? 
手动设置超过60帧时这个功能很重要。
I can't find "Unlock monitor refresh rate" in the latest version(2.1.3.0)
It's important when gaming over 60fps with a high refresh rate screen

**Comment by hoangcaominh** [comment]
It was removed in this commit 348f9eba556e207b132e6c0997d665dbf5f158be

**Comment by STARBOWBREAK6** [comment]
Why? I think this feature is useful.

**Comment by 32th-System** [comment]
Was it?

**Comment by STARBOWBREAK6** [comment]
Yes.
75 or higher FPS is a challenging goal and thprac is the tool to adjust FPS.
For example, I use a 144 Hz monitor to play a game at 90FPS.
If this feature was enabled , my graphics card will output 90 frames per second.
Otherwise it will only output 60 frames per second and cause partial frame missing.

**Comment by STARBOWBREAK6** [comment]
So, will you add this feature back in a future version?
